<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.30">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Bill Cresko">

<title>Week 8a - Statistics for Bioengineering – BioEngineering Statistics Winter 2026</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-de070a7b0ab54f8780927367ac907214.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-f7fe251563e67c05764dc4775ff48cfc.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">BioEngineering Statistics Winter 2026</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../Syllabus.html"> 
<span class="menu-text">Syllabus</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../Policies.html"> 
<span class="menu-text">Policies</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../Schedule.html"> 
<span class="menu-text">Schedule</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../Lectures.html"> 
<span class="menu-text">Lectures</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../Homework.html"> 
<span class="menu-text">Homeworks</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../Software.html"> 
<span class="menu-text">Software</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../Resources.html"> 
<span class="menu-text">Resources</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#this-week" id="toc-this-week" class="nav-link active" data-scroll-target="#this-week">This week</a></li>
  <li><a href="#design-principles-for-planning-a-good-experiment" id="toc-design-principles-for-planning-a-good-experiment" class="nav-link" data-scroll-target="#design-principles-for-planning-a-good-experiment">Design principles for planning a good experiment</a>
  <ul class="collapse">
  <li><a href="#what-is-an-experimental-study" id="toc-what-is-an-experimental-study" class="nav-link" data-scroll-target="#what-is-an-experimental-study">What is an experimental study?</a></li>
  <li><a href="#mount-everest-example" id="toc-mount-everest-example" class="nav-link" data-scroll-target="#mount-everest-example">Mount Everest example</a></li>
  <li><a href="#mount-everest-example-1" id="toc-mount-everest-example-1" class="nav-link" data-scroll-target="#mount-everest-example-1">Mount Everest example</a></li>
  <li><a href="#clinical-trials" id="toc-clinical-trials" class="nav-link" data-scroll-target="#clinical-trials">Clinical Trials</a></li>
  <li><a href="#example-of-a-clinical-trial" id="toc-example-of-a-clinical-trial" class="nav-link" data-scroll-target="#example-of-a-clinical-trial">Example of a clinical trial</a></li>
  <li><a href="#outcome-of-the-clinical-trial" id="toc-outcome-of-the-clinical-trial" class="nav-link" data-scroll-target="#outcome-of-the-clinical-trial">Outcome of the clinical trial</a></li>
  <li><a href="#design-components-of-a-clinical-trial" id="toc-design-components-of-a-clinical-trial" class="nav-link" data-scroll-target="#design-components-of-a-clinical-trial">Design components of a clinical trial</a></li>
  <li><a href="#simultaneous-control-group" id="toc-simultaneous-control-group" class="nav-link" data-scroll-target="#simultaneous-control-group">1. Simultaneous control group</a></li>
  <li><a href="#randomization" id="toc-randomization" class="nav-link" data-scroll-target="#randomization">2. Randomization</a></li>
  <li><a href="#randomization-1" id="toc-randomization-1" class="nav-link" data-scroll-target="#randomization-1">2. Randomization</a></li>
  <li><a href="#randomization-types" id="toc-randomization-types" class="nav-link" data-scroll-target="#randomization-types">2. Randomization Types</a></li>
  <li><a href="#random-sampling-approaches" id="toc-random-sampling-approaches" class="nav-link" data-scroll-target="#random-sampling-approaches">2. Random sampling approaches</a></li>
  <li><a href="#blinding" id="toc-blinding" class="nav-link" data-scroll-target="#blinding">3. Blinding</a></li>
  <li><a href="#blinding-1" id="toc-blinding-1" class="nav-link" data-scroll-target="#blinding-1">3. Blinding</a></li>
  <li><a href="#replication" id="toc-replication" class="nav-link" data-scroll-target="#replication">4. Replication</a></li>
  <li><a href="#replication-1" id="toc-replication-1" class="nav-link" data-scroll-target="#replication-1">4. Replication</a></li>
  <li><a href="#pseudoreplication" id="toc-pseudoreplication" class="nav-link" data-scroll-target="#pseudoreplication">4. (Pseudo)replication</a></li>
  <li><a href="#balance" id="toc-balance" class="nav-link" data-scroll-target="#balance">5. Balance</a></li>
  <li><a href="#blocking" id="toc-blocking" class="nav-link" data-scroll-target="#blocking">6. Blocking</a></li>
  <li><a href="#what-if-you-cant-do-experiments" id="toc-what-if-you-cant-do-experiments" class="nav-link" data-scroll-target="#what-if-you-cant-do-experiments">What if you can’t do experiments?</a></li>
  </ul></li>
  <li><a href="#general-linear-mixed-models" id="toc-general-linear-mixed-models" class="nav-link" data-scroll-target="#general-linear-mixed-models">General Linear Mixed Models</a>
  <ul class="collapse">
  <li><a href="#what-is-a-glmm" id="toc-what-is-a-glmm" class="nav-link" data-scroll-target="#what-is-a-glmm">What is a GLMM?</a></li>
  <li><a href="#attributes-of-mixed-effects-models" id="toc-attributes-of-mixed-effects-models" class="nav-link" data-scroll-target="#attributes-of-mixed-effects-models">Attributes of mixed effects models</a></li>
  <li><a href="#assumptions-of-mixed-effects-models" id="toc-assumptions-of-mixed-effects-models" class="nav-link" data-scroll-target="#assumptions-of-mixed-effects-models">Assumptions of mixed-effects models</a></li>
  <li><a href="#hypotheses-for-model-3-anova-factorial-design-with-mixed-effects" id="toc-hypotheses-for-model-3-anova-factorial-design-with-mixed-effects" class="nav-link" data-scroll-target="#hypotheses-for-model-3-anova-factorial-design-with-mixed-effects">Hypotheses for Model 3 ANOVA Factorial Design With Mixed Effects</a></li>
  </ul></li>
  <li><a href="#parallel-slopes-mixed-model-aka-analysis-of-covariance-ancova" id="toc-parallel-slopes-mixed-model-aka-analysis-of-covariance-ancova" class="nav-link" data-scroll-target="#parallel-slopes-mixed-model-aka-analysis-of-covariance-ancova">Parallel Slopes Mixed Model (aka Analysis of Covariance (ANCOVA))</a>
  <ul class="collapse">
  <li><a href="#brain-body-size-neaderthals-as-compared-to-humans" id="toc-brain-body-size-neaderthals-as-compared-to-humans" class="nav-link" data-scroll-target="#brain-body-size-neaderthals-as-compared-to-humans">Brain &amp; body size | neaderthals as compared to humans</a></li>
  <li><a href="#brain-body-size-neaderthals-as-compared-to-humans-1" id="toc-brain-body-size-neaderthals-as-compared-to-humans-1" class="nav-link" data-scroll-target="#brain-body-size-neaderthals-as-compared-to-humans-1">Brain &amp; body size | neaderthals as compared to humans</a></li>
  <li><a href="#brain-body-size-neaderthals-as-compared-to-humans-2" id="toc-brain-body-size-neaderthals-as-compared-to-humans-2" class="nav-link" data-scroll-target="#brain-body-size-neaderthals-as-compared-to-humans-2">Brain &amp; body size | neaderthals as compared to humans</a></li>
  <li><a href="#parallel-slopes-mixed-model" id="toc-parallel-slopes-mixed-model" class="nav-link" data-scroll-target="#parallel-slopes-mixed-model">Parallel Slopes Mixed Model</a></li>
  <li><a href="#parallel-slopes-model---r-interlude" id="toc-parallel-slopes-model---r-interlude" class="nav-link" data-scroll-target="#parallel-slopes-model---r-interlude">Parallel Slopes Model - R Interlude</a></li>
  <li><a href="#parallel-slopes-model---r-interlude-1" id="toc-parallel-slopes-model---r-interlude-1" class="nav-link" data-scroll-target="#parallel-slopes-model---r-interlude-1">Parallel Slopes Model - R Interlude</a></li>
  <li><a href="#parallel-slopes-model---r-interlude-2" id="toc-parallel-slopes-model---r-interlude-2" class="nav-link" data-scroll-target="#parallel-slopes-model---r-interlude-2">Parallel Slopes Model - R Interlude</a></li>
  <li><a href="#parallel-slopes-model---r-interlude-3" id="toc-parallel-slopes-model---r-interlude-3" class="nav-link" data-scroll-target="#parallel-slopes-model---r-interlude-3">Parallel Slopes Model - R Interlude</a></li>
  <li><a href="#parallel-slopes-model---r-interlude-4" id="toc-parallel-slopes-model---r-interlude-4" class="nav-link" data-scroll-target="#parallel-slopes-model---r-interlude-4">Parallel Slopes Model - R Interlude</a></li>
  <li><a href="#parallel-slopes-model---r-interlude-5" id="toc-parallel-slopes-model---r-interlude-5" class="nav-link" data-scroll-target="#parallel-slopes-model---r-interlude-5">Parallel Slopes Model - R Interlude</a></li>
  <li><a href="#parallel-slopes-mixed-model-1" id="toc-parallel-slopes-mixed-model-1" class="nav-link" data-scroll-target="#parallel-slopes-mixed-model-1">Parallel Slopes Mixed Model</a></li>
  </ul></li>
  <li><a href="#interaction-mixed-model" id="toc-interaction-mixed-model" class="nav-link" data-scroll-target="#interaction-mixed-model">Interaction Mixed Model</a>
  <ul class="collapse">
  <li><a href="#interaction-mixed-model-1" id="toc-interaction-mixed-model-1" class="nav-link" data-scroll-target="#interaction-mixed-model-1">Interaction Mixed Model</a></li>
  <li><a href="#interaction-mixed-model-2" id="toc-interaction-mixed-model-2" class="nav-link" data-scroll-target="#interaction-mixed-model-2">Interaction Mixed Model</a></li>
  <li><a href="#interaction-mixed-model-3" id="toc-interaction-mixed-model-3" class="nav-link" data-scroll-target="#interaction-mixed-model-3">Interaction Mixed Model</a></li>
  <li><a href="#interaction-mixed-model-4" id="toc-interaction-mixed-model-4" class="nav-link" data-scroll-target="#interaction-mixed-model-4">Interaction Mixed Model</a></li>
  <li><a href="#interaction-mixed-model-5" id="toc-interaction-mixed-model-5" class="nav-link" data-scroll-target="#interaction-mixed-model-5">Interaction Mixed Model</a></li>
  </ul></li>
  <li><a href="#section" id="toc-section" class="nav-link" data-scroll-target="#section"></a></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="Week8a.html"><i class="bi bi-file-slides"></i>RevealJS</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Week 8a - Statistics for Bioengineering</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Bill Cresko </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'ggplot2' was built under R version 4.4.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'tidyr' was built under R version 4.4.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'readr' was built under R version 4.4.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.6
✔ forcats   1.0.1     ✔ stringr   1.6.0
✔ ggplot2   4.0.1     ✔ tibble    3.3.0
✔ lubridate 1.9.4     ✔ tidyr     1.3.2
✔ purrr     1.2.0     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gt)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'gt' was built under R version 4.4.3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tibble)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="this-week" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="this-week">This week</h2>
<ul>
<li><p>Key principles of experimental design</p></li>
<li><p>Linear Mixed Models (GLMMs)</p></li>
<li><p>Chi-square tests</p></li>
<li><p>Generalized Linear Models - Logistic and Poisson Regression</p></li>
</ul>
</section>
<section id="design-principles-for-planning-a-good-experiment" class="level1">
<h1>Design principles for planning a good experiment</h1>
<section id="what-is-an-experimental-study" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="what-is-an-experimental-study">What is an experimental study?</h2>
<ul>
<li>In an <strong>experimental study</strong> the researcher assigns treatments to units</li>
<li>In an <strong>observational study</strong> nature does the assigning of treatments to units</li>
<li>The crucial advantage of experiments derives from <strong>the random assignment of treatments to units</strong></li>
<li>Randomization <strong>minimizes the influence of confounding variables</strong></li>
<li>Allows us to infer <strong>cause and effect</strong> more easily (or at all)</li>
</ul>
</section>
<section id="mount-everest-example" class="level2 vcenter flexbox">
<h2 class="vcenter flexbox anchored" data-anchor-id="mount-everest-example">Mount Everest example</h2>
<p>Survival of climbers of Mount Everest is higher for individuals taking supplemental oxygen than those who don’t.</p>
<p><strong>Why?</strong></p>
</section>
<section id="mount-everest-example-1" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="mount-everest-example-1">Mount Everest example</h2>
<ul>
<li>One possibility is that supplemental oxygen (explanatory variable) really does cause higher survival (response variable).</li>
<li>The other is that the two variables are associated because other variables affect both supplemental oxygen and survival.</li>
<li>Use of supplemental oxygen might be a benign indicator of a greater overall preparedness of the climbers that use it.</li>
<li>Variables (like preparedness) that distort the causal relationship between the measured variables of interest (oxygen use and survival) are called <strong>confounding variables</strong></li>
</ul>
</section>
<section id="clinical-trials" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="clinical-trials">Clinical Trials</h2>
<ul>
<li>The gold standard of experimental designs is the <strong>clinical trial</strong></li>
<li>Experimental design in all areas of biology have been informed by procedures used in clinical trials</li>
<li>A clinical trial is an experimental study in which two or more treatments are assigned to human subjects</li>
<li>The design of clinical trials has been refined because the cost of making a mistake with human subjects is so high</li>
<li>Experiments on nonhuman subjects are simply called “laboratory experiments”or “field experiments”</li>
</ul>
</section>
<section id="example-of-a-clinical-trial" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="example-of-a-clinical-trial">Example of a clinical trial</h2>
<ul>
<li>Transmission of the HIV-1 virus via sex workers contributes to the rapid spread of AIDS in Africa</li>
<li>The spermicide nonoxynol-9 had shown <em>in vitro</em> activity against HIV-1, which motivated a clinical trial by van Damme et al.&nbsp;(2002).</li>
<li>They tested whether a vaginal gel containing the chemical would reduce the risk of acquiring the disease by female sex workers.</li>
<li>Data were gathered on a volunteer sample of 765 HIV-free sex-workers in six clinics in Asia and Africa.</li>
<li>Two gel treatments were assigned randomly to women at each clinic:
<ul>
<li>One gel contained nonoxynol-9</li>
<li>the other was a placebo.</li>
</ul></li>
<li>Neither the subjects nor the researchers making observations at the clinics knew who received the treatment and who got the placebo.</li>
</ul>
</section>
<section id="outcome-of-the-clinical-trial" class="level2 flexbox vcenter smaller">
<h2 class="flexbox vcenter smaller anchored" data-anchor-id="outcome-of-the-clinical-trial">Outcome of the clinical trial</h2>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/images_6a.005.jpeg" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:90.0%"></p>
</figure>
</div>
</div>
</div>
<ul>
<li>Note that these are count data but clinical trials could involve continuous data</li>
<li>We will use these data on Thursday for our Chi-square analyses</li>
<li>Also there is another variable - what is the nature of that variable?</li>
</ul>
</section>
<section id="design-components-of-a-clinical-trial" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="design-components-of-a-clinical-trial">Design components of a clinical trial</h2>
<p>The goal of experimental design is to eliminate bias and to reduce sampling error when estimating and testing effects of one variable on another.</p>
<ul>
<li>To reduce bias, the experiment included:
<ul>
<li><strong>Simultaneous control group</strong>: study included both the treatment of interest and a control group (the women receiving the placebo).</li>
<li><strong>Randomization</strong>: treatments were randomly assigned to women at each clinic.</li>
<li><strong>Blinding</strong>: neither the subjects nor the clinicians knew which women were assigned which treatment.</li>
</ul></li>
<li>To reduce the effects of sampling error, the experiment included:
<ul>
<li><strong>Replication</strong>: study was carried out on multiple independent subjects.</li>
<li><strong>Balance</strong>: number of women was nearly equal in the two groups at every clinic.</li>
<li><strong>Blocking</strong>: subjects were grouped according to the clinic they attended, yielding multiple repetitions of the same experiment in different settings (“blocks”).</li>
</ul></li>
</ul>
</section>
<section id="simultaneous-control-group" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="simultaneous-control-group">1. Simultaneous control group</h2>
<ul>
<li>In clinical trials either a placebo or the currently accepted treatment should be provided.</li>
<li>In experiments requiring intrusive methods to administer treatment, such as
<ul>
<li>injections</li>
<li>surgery</li>
<li>restraint</li>
<li>confinement</li>
</ul></li>
<li>the control subjects should be perturbed in the same way as the other subjects, except for the treatment itself, as far as ethical considerations permit.</li>
<li>The “sham operation”, in which surgery is carried out without the experimental treatment itself, is an example.</li>
<li>In field experiments, applying a treatment of interest may physically disturb the plots receiving it and the surrounding areas, perhaps by trampling the ground by the researchers.</li>
<li>Ideally, the same disturbance should be applied to the control plots.</li>
</ul>
</section>
<section id="randomization" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="randomization">2. Randomization</h2>
<ul>
<li>The researcher should randomize assignment of treatments to units or subjects</li>
<li>Chance rather than conscious or unconscious decision determines which units end up receiving the treatment and which the control</li>
<li>Randomization breaks the association between possible confounding variables and the explanatory variable</li>
<li>Randomization doesn’t eliminate the variation contributed by confounding variables, only their correlation with treatment</li>
<li>Randomization ensures that variation from confounding variables is similar between the different treatment groups.</li>
</ul>
</section>
<section id="randomization-1" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="randomization-1">2. Randomization</h2>
<ul>
<li>Randomization should be carried out using a random process:
<ul>
<li>List all n subjects, one per row, in a computer spreadsheet.</li>
<li>Use the computer to give each individual a random number.</li>
<li>Assign treatment A to those subjects receiving the lowest numbers and treatment B to those with the highest numbers.</li>
</ul></li>
<li>Other ways of assigning treatments to subjects are almost always inferior because they do not eliminate the effects of confounding variables.</li>
<li>“Haphazard” assignment, in which the researcher chooses a treatment while trying to make it random, has repeatedly been shown to be non-random and prone to bias.</li>
</ul>
</section>
<section id="randomization-types" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="randomization-types">2. Randomization Types</h2>
<ul>
<li><p><strong>Completely randomized design</strong> - all subjects are placed to treatment or control with equal probability</p></li>
<li><p><strong>Randomized block</strong> - first broken into groups (e.g.&nbsp;age or gender) then assigned to treatment groups at random</p></li>
<li><p><strong>Matched pair design</strong> - subjects are paired by similarity before being randomly assigned to treatment groups</p></li>
</ul>
</section>
<section id="random-sampling-approaches" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="random-sampling-approaches">2. Random sampling approaches</h2>
<ul>
<li><strong>Simple random sample</strong> - every sample has equal probability of being chosen</li>
<li><strong>Stratified sample</strong> - subjects are randomly divided into groups then a simple random sample are taken from each</li>
<li><strong>Cluster sample</strong> - subjects are divided into similar groups, usually naturally occurring, and then a simple random samples of clusters is then taken and every member of the cluster is included in the sample</li>
<li><strong>Multistage sampling</strong> - First clusters are random sampled, and then random samples are take from each cluster.</li>
<li><strong>Systematic sample</strong> - members of a sample are chosen in a pre-determined ways. e.g Choose every 20th person coming into a store</li>
</ul>
</section>
<section id="blinding" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="blinding">3. Blinding</h2>
<ul>
<li><strong>Blinding</strong> is the process of concealing information from participants (sometimes including researchers) about which subjects receive which treatment.</li>
<li>Blinding prevents <strong>subjects</strong> and <strong>researchers</strong> from changing their behavior, consciously or unconsciously, as a result of knowing which treatment they were receiving or administering.</li>
<li>For example, studies showing that acupuncture has a significant effect on back pain are limited to those without blinding.</li>
<li>Reviews of medical studies have revealed that studies carried out without double- blinding exaggerated treatment effects by 16% on average compared with studies carried out with double-blinding (Jüni et al.&nbsp;2001).</li>
<li>Bebarta et al.(2003) reviewed 290 two-treatment experiments carried out on animals or on cell lines. The odds of detecting a positive effect of treatment were more than threefold higher in studies without blinding than in studies with blinding.</li>
<li>Blinding can be incorporated into experiments on nonhuman subjects using coded tags that identify the subject to a “blind” observer without revealing the treatment (and who measures units from different treatments in random order).</li>
</ul>
</section>
<section id="blinding-1" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="blinding-1">3. Blinding</h2>
<ul>
<li>In a <strong>single-blind experiment</strong>, the subjects are unaware of the treatment that they have been assigned.
<ul>
<li>Treatments must be indistinguishable to subjects, which prevents them from responding differently according to knowledge of treatment.</li>
<li>Blinding can also be a concern in non-human studies where animals respond to stimuli</li>
</ul></li>
<li>In a <strong>double-blind experiment</strong> the researchers administering the treatments and measuring the response are also unaware of which subjects are receiving which treatments
<ul>
<li>Researchers sometimes have pet hypotheses, and they might treat experimental subjects in different ways depending on their hopes for the outcome</li>
<li>Many response variables are difficult to measure and require some subjective interpretation, which makes the results prone to a bias</li>
<li>Researchers are naturally more interested in the treated subjects than the control subjects, and this increased attention can itself result in improved response</li>
</ul></li>
</ul>
</section>
<section id="replication" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="replication">4. Replication</h2>
<ul>
<li><p>Replication is the assignment of each treatment to multiple, independent experimental units.</p></li>
<li><p>The goal of experiments is to estimate and test treatment effects against the background of variation between individuals (“noise”) caused by other variables</p></li>
<li><p>Without replication, we would not know whether response differences were due to the treatments or just chance differences between the treatments caused by other factors.</p></li>
<li><p>One way to reduce noise is to make the experimental conditions constant</p></li>
<li><p>However, highly constant experimental conditions might not be feasible nor desirable</p></li>
<li><p>By limiting the conditions of an experiment, we also limit the generality of the results</p></li>
<li><p>Another way to make treatment effects stand out is to include extreme treatments and to replicate the data.</p></li>
</ul>
</section>
<section id="replication-1" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="replication-1">4. Replication</h2>
<ul>
<li>Studies that use more units (i.e.&nbsp;that have larger sample sizes) will have smaller standard errors and a higher probability of getting the correct answer from a hypothesis test.</li>
<li>Larger samples mean more information, and more information means better estimates and more powerful tests.</li>
<li>Replication is not about the number of plants or animals used, but the number of independent units in the experiment. An “experimental unit” is the independent unit to which treatments are assigned.</li>
<li>The figure shows three experimental designs used to compare plant growth under two temperature treatments (indicated by the shading of the pots). The first two designs are un-replicated.</li>
</ul>
</section>
<section id="pseudoreplication" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="pseudoreplication">4. (Pseudo)replication</h2>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/images_6a.006.jpeg" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:90.0%"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="balance" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="balance">5. Balance</h2>
<ul>
<li>A study design is balanced if all treatments have the same sample size.</li>
<li>Conversely, a design is unbalanced if there are unequal sample sizes between treatments.</li>
<li>Balance is a second way to reduce the influence of sampling error on estimation and hypothesis testing.</li>
<li>To appreciate this, look again at the equation for the standard error of the difference between two treatment means.</li>
<li>For a fixed total number of experimental units, n1 + n2, the standard error is smallest when n1 and n2 are equal.</li>
<li>Balance has other benefits. For example, ANOVA is more robust to departures from the assumption of equal variances when designs are balanced or nearly so.</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/images_6a.007.jpeg" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="blocking" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="blocking">6. Blocking</h2>
<ul>
<li>Blocking is the grouping of experimental units that have similar properties. Within each block, treatments are randomly assigned to experimental units.</li>
<li>Blocking essentially repeats the same, completely randomized experiment multiple times, once for each block.</li>
<li>Differences between treatments are only evaluated within blocks, and in this way the component of variation arising from differences between blocks are controlled for.</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/images_6a.008.jpeg" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="what-if-you-cant-do-experiments" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="what-if-you-cant-do-experiments">What if you can’t do experiments?</h2>
<ul>
<li>Experimental studies are not always feasible, in which case we must fall back upon observational studies.</li>
<li>The best observational studies incorporate as many of the features of good experimental design as possible to minimize bias (e.g., blinding) and the impact of sampling error (e.g., replication, balance, blocking, and even extreme treatments) except for one: randomization.</li>
<li>Randomization is out of the question, because in an observational study the researcher does not assign treatments to subjects.</li>
<li>Two strategies are used to limit the effects of confounding variables on a difference between treatments in a controlled observational study: matching; and adjusting for known confounding variables (covariates).</li>
<li>But beware - there could always be a co-variate that you didn’t include!</li>
</ul>
<hr>
</section>
</section>
<section id="general-linear-mixed-models" class="level1">
<h1>General Linear Mixed Models</h1>
<section id="what-is-a-glmm" class="level2">
<h2 class="anchored" data-anchor-id="what-is-a-glmm">What is a GLMM?</h2>
<ul>
<li>General Linear Mixed Model (<strong>GLMM</strong>)</li>
<li>A continuous response variable with a mix of continuous and categorical predictor variables</li>
<li>GLMM’s can be used to model random effects</li>
</ul>
</section>
<section id="attributes-of-mixed-effects-models" class="level2 flexbox vcenter smaller">
<h2 class="flexbox vcenter smaller anchored" data-anchor-id="attributes-of-mixed-effects-models">Attributes of mixed effects models</h2>
<ul>
<li>Linear models that include both fixed and random effects.</li>
<li>The model is split into fixed and random parts:
<ul>
<li>Fixed effects influence mean of the response variable Y.</li>
<li>Random effects influence the variance of Y.</li>
</ul></li>
<li>There is a different error variance for each level of grouping.</li>
<li>Estimation and testing is based on restricted maximum likelihood, which can handle unequal sample size.</li>
<li>P-values for fixed effects are conservative when design unbalanced.</li>
<li>We can use <code>lm</code> for simple models (which we’ll do today)</li>
<li>More complicated models are better performed using the <code>nlme</code> &amp; <code>lme4</code> packages in <code>R</code>.</li>
</ul>
</section>
<section id="assumptions-of-mixed-effects-models" class="level2 flexbox vcenter smaller">
<h2 class="flexbox vcenter smaller anchored" data-anchor-id="assumptions-of-mixed-effects-models">Assumptions of mixed-effects models</h2>
<ul>
<li>Variation within groups follows a normal distribution with equal variance among groups.</li>
<li>Groups are randomly sampled from “population” of groups.</li>
<li>Group means follow a normal distribution.</li>
<li>Measurements within groups are independent.</li>
</ul>
</section>
<section id="hypotheses-for-model-3-anova-factorial-design-with-mixed-effects" class="level2 flexbox vcenter">
<h2 class="flexbox vcenter anchored" data-anchor-id="hypotheses-for-model-3-anova-factorial-design-with-mixed-effects">Hypotheses for Model 3 ANOVA Factorial Design With Mixed Effects</h2>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/images_7b.003.jpeg" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:90.0%"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="parallel-slopes-mixed-model-aka-analysis-of-covariance-ancova" class="level1">
<h1>Parallel Slopes Mixed Model (aka Analysis of Covariance (ANCOVA))</h1>
<section id="brain-body-size-neaderthals-as-compared-to-humans" class="level2 flexbox vcenter">
<h2 class="flexbox vcenter anchored" data-anchor-id="brain-body-size-neaderthals-as-compared-to-humans">Brain &amp; body size | neaderthals as compared to humans</h2>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/images_7b.005.jpeg" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:90.0%"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="brain-body-size-neaderthals-as-compared-to-humans-1" class="level2 flexbox vcenter">
<h2 class="flexbox vcenter anchored" data-anchor-id="brain-body-size-neaderthals-as-compared-to-humans-1">Brain &amp; body size | neaderthals as compared to humans</h2>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/images_7b.006.jpeg" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:90.0%"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="brain-body-size-neaderthals-as-compared-to-humans-2" class="level2 flexbox vcenter">
<h2 class="flexbox vcenter anchored" data-anchor-id="brain-body-size-neaderthals-as-compared-to-humans-2">Brain &amp; body size | neaderthals as compared to humans</h2>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/images_7b.007.jpeg" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:90.0%"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="parallel-slopes-mixed-model" class="level2 flexbox vcenter">
<h2 class="flexbox vcenter anchored" data-anchor-id="parallel-slopes-mixed-model">Parallel Slopes Mixed Model</h2>
<ul>
<li>Mixture of regression and ANOVA</li>
<li>Response is still a normally distributed continuous variable</li>
<li>One or more continuous predictor variables (covariates)</li>
<li>Sometimes the covariates are of biological interest</li>
<li>Most often we want to remove unexplained variance</li>
<li>In this way they are similar to a blocking variable in ANOVA</li>
<li>Operationally, similar to regular ANOVA in which the group and overall means are replaced by group and overall relationships</li>
</ul>
</section>
<section id="parallel-slopes-model---r-interlude" class="level2">
<h2 class="anchored" data-anchor-id="parallel-slopes-model---r-interlude">Parallel Slopes Model - R Interlude</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tibble)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>heart_rate_df <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"mouse_rat_heart.csv"</span>, <span class="at">header =</span> <span class="cn">TRUE</span>)</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(heart_rate_df, <span class="fu">aes</span>(<span class="at">x =</span> temp, <span class="at">y =</span> heart_rate, <span class="at">col =</span> species)) <span class="sc">+</span> </span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="parallel-slopes-model---r-interlude-1" class="level2">
<h2 class="anchored" data-anchor-id="parallel-slopes-model---r-interlude-1">Parallel Slopes Model - R Interlude</h2>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Week8a_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="parallel-slopes-model---r-interlude-2" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="parallel-slopes-model---r-interlude-2">Parallel Slopes Model - R Interlude</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tibble)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>heart_rate_df <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"mouse_rat_heart.csv"</span>, <span class="at">header =</span> <span class="cn">TRUE</span>)</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>model_additive <span class="ot">&lt;-</span> <span class="fu">lm</span>(heart_rate <span class="sc">~</span> temp <span class="sc">+</span> species, <span class="at">data =</span> heart_rate_df)</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_additive)</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>new_heart_rate_df <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">species =</span> <span class="fu">c</span>(<span class="st">"mouse"</span>, <span class="st">"mouse"</span>, <span class="st">"mouse"</span>, <span class="st">"rat"</span>, <span class="st">"rat"</span>, <span class="st">"rat"</span>),</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">temp =</span> <span class="fu">c</span>(<span class="dv">24</span>, <span class="dv">26</span>, <span class="dv">28</span>, <span class="dv">24</span>, <span class="dv">26</span>, <span class="dv">28</span>)</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(model_additive, new_heart_rate_df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="parallel-slopes-model---r-interlude-3" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="parallel-slopes-model---r-interlude-3">Parallel Slopes Model - R Interlude</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = heart_rate ~ temp + species, data = heart_rate_df)

Residuals:
    Min      1Q  Median      3Q     Max 
-3.0128 -1.1296 -0.3912  0.9650  3.7800 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  -7.21091    2.55094  -2.827  0.00858 ** 
temp          3.60275    0.09729  37.032  &lt; 2e-16 ***
speciesrat  -10.06529    0.73526 -13.689 6.27e-14 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.786 on 28 degrees of freedom
Multiple R-squared:  0.9896,    Adjusted R-squared:  0.9888 
F-statistic:  1331 on 2 and 28 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>       1        2        3        4        5        6 
79.25516 86.46067 93.66617 69.18987 76.39538 83.60088 </code></pre>
</div>
</div>
</section>
<section id="parallel-slopes-model---r-interlude-4" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="parallel-slopes-model---r-interlude-4">Parallel Slopes Model - R Interlude</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tibble)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>heart_rate_df <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"mouse_rat_heart.csv"</span>, <span class="at">header =</span> <span class="cn">TRUE</span>)</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>model_interactive <span class="ot">&lt;-</span> <span class="fu">lm</span>(heart_rate <span class="sc">~</span> temp <span class="sc">*</span> species, <span class="at">data =</span> heart_rate_df)</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_interactive)</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>new_heart_rate_df <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">species =</span> <span class="fu">c</span>(<span class="st">"mouse"</span>, <span class="st">"mouse"</span>, <span class="st">"mouse"</span>, <span class="st">"rat"</span>, <span class="st">"rat"</span>, <span class="st">"rat"</span>),</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">temp =</span> <span class="fu">c</span>(<span class="dv">24</span>, <span class="dv">26</span>, <span class="dv">28</span>, <span class="dv">24</span>, <span class="dv">26</span>, <span class="dv">28</span>)</span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(model_interactive, new_heart_rate_df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="parallel-slopes-model---r-interlude-5" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="parallel-slopes-model---r-interlude-5">Parallel Slopes Model - R Interlude</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = heart_rate ~ temp * species, data = heart_rate_df)

Residuals:
    Min      1Q  Median      3Q     Max 
-3.7031 -1.3417 -0.1235  0.8100  3.6330 

Coefficients:
                Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)     -11.0408     4.1515  -2.659    0.013 *  
temp              3.7514     0.1601  23.429   &lt;2e-16 ***
speciesrat       -4.3484     4.9617  -0.876    0.389    
temp:speciesrat  -0.2340     0.2009  -1.165    0.254    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.775 on 27 degrees of freedom
Multiple R-squared:  0.9901,    Adjusted R-squared:  0.989 
F-statistic: 898.9 on 3 and 27 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>       1        2        3        4        5        6 
78.99389 86.49678 93.99967 69.02983 76.06475 83.09967 </code></pre>
</div>
</div>
</section>
<section id="parallel-slopes-mixed-model-1" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="parallel-slopes-mixed-model-1">Parallel Slopes Mixed Model</h2>
<p><span class="math display">\[ y = \beta_0 + \beta_1x_1 + \beta_2x_2 + \epsilon \]</span> where</p>
<p><span class="math display">\[
y = \left\{
\begin{aligned}
    &amp; \beta_0 + \beta_1x_1 + \epsilon \\
    &amp;(\beta_0 + \beta_2) +\beta_1x_1 + \epsilon
\end{aligned}
\right.
\]</span></p>
<ul>
<li>Where the intercepts are different from one another but the slopes are not - R gives those estimates in that exact order</li>
</ul>
<p><span class="math display">\[
y = \left\{
\begin{aligned}
    &amp; -7.21091 + 3.60275x_1  \\
    &amp;(-7.21091 -10.06529) +3.60275x_1
\end{aligned}
\right.
\]</span></p>
</section>
</section>
<section id="interaction-mixed-model" class="level1">
<h1>Interaction Mixed Model</h1>
<section id="interaction-mixed-model-1" class="level2">
<h2 class="anchored" data-anchor-id="interaction-mixed-model-1">Interaction Mixed Model</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(modeldata)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="fu">theme_set</span>(<span class="fu">theme_minimal</span>())</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(penguins)</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>penguins_sm <span class="ot">&lt;-</span> <span class="fu">filter</span>(penguins, species <span class="sc">!=</span> <span class="st">"Adelie"</span>)</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(penguins_sm, <span class="fu">aes</span>(<span class="at">x =</span> flipper_length_mm,</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>                        <span class="at">y =</span> body_mass_g,</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>                        <span class="at">col =</span> species)) <span class="sc">+</span> </span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="interaction-mixed-model-2" class="level2">
<h2 class="anchored" data-anchor-id="interaction-mixed-model-2">Interaction Mixed Model</h2>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 1 row containing non-finite outside the scale range
(`stat_smooth()`).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 1 row containing missing values or values outside the scale range
(`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Week8a_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="interaction-mixed-model-3" class="level2">
<h2 class="anchored" data-anchor-id="interaction-mixed-model-3">Interaction Mixed Model</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(modeldata)</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="fu">theme_set</span>(<span class="fu">theme_minimal</span>())</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(penguins)</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>penguins_sm <span class="ot">&lt;-</span> <span class="fu">filter</span>(penguins, species <span class="sc">!=</span> <span class="st">"Adelie"</span>)</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(body_mass_g <span class="sc">~</span> flipper_length_mm <span class="sc">*</span> species,</span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>            <span class="at">data =</span> penguins_sm)</span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="interaction-mixed-model-4" class="level2">
<h2 class="anchored" data-anchor-id="interaction-mixed-model-4">Interaction Mixed Model</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = body_mass_g ~ flipper_length_mm * species, data = penguins_sm)

Residuals:
    Min      1Q  Median      3Q     Max 
-911.18 -215.38  -42.69  162.67 1015.71 

Coefficients:
                                 Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                     -3037.196   1138.679  -2.667  0.00832 ** 
flipper_length_mm                  34.573      5.811   5.950  1.3e-08 ***
speciesGentoo                   -3750.085   1534.769  -2.443  0.01548 *  
flipper_length_mm:speciesGentoo    20.049      7.496   2.674  0.00815 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 339.2 on 187 degrees of freedom
  (1 observation deleted due to missingness)
Multiple R-squared:  0.8205,    Adjusted R-squared:  0.8176 
F-statistic: 284.9 on 3 and 187 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<ul>
<li><p>Make a dummy data set of values for Gentoo and Chinstrap Penguins</p></li>
<li><p>Use the interaction model that you fit to make new predictions for those values</p></li>
</ul>
</section>
<section id="interaction-mixed-model-5" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="interaction-mixed-model-5">Interaction Mixed Model</h2>
<p><span class="math display">\[
x_2 = \left\{
\begin{aligned}
    &amp; 0 \qquad \text{for Chinstrap} \\
    &amp; 1 \qquad \text{for Gentoo}
\end{aligned}
\right.
\]</span> <span class="math display">\[ y = \beta_0 + \beta_1x_1 + \beta_2x_2 + \beta_3x_1x_2 + \epsilon \]</span></p>
<p><span class="math display">\[
y = \left\{
\begin{aligned}
    &amp; \beta_0 + \beta_1x_1 + \epsilon \\
    &amp;(\beta_0 + \beta_2) +(\beta_1 +\beta_3)x_1 + \epsilon
\end{aligned}
\right.
\]</span> - Where the intercepts are different from one another but the slopes are not - Again R gives those estimates in that exact order</p>
<p><span class="math display">\[
y = \left\{
\begin{aligned}
    &amp; -3037.196 + 34.573x_1  \\
    &amp;(-3037.196 - 3750.085) + (34.573 + 20.049)x_1
\end{aligned}
\right.
\]</span></p>
<hr>
</section>
</section>
<section id="section" class="level1">
<h1></h1>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>